### ISSUE TITLE
Fix Refresh files after uploading in PDF Viewer Block

### ISSUE THREAD

**Issue by Gowrishankar-Palanisamy** [SEMOSS/semoss-ui#1711]
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

Attached the bug link 

[https://github.com/SEMOSS/semoss-ui/issues/1684](url)

### Expected Result

After uploading the file, the files tab should automatically refresh and show the uploaded file

### Actual Results

After uploading the file, the files tab was not refreshing automatically and not showing the uploaded file.

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

**Comment by Gowrishankar-Palanisamy** [comment]
Fixed the issue, Kindly review the flow @ehynd , @johbaxter 

https://github.com/user-attachments/assets/142b91ee-630a-44fe-a2c3-27959d109de5

**Comment by ehynd** [comment]
Looks good, thank you!

**Comment by Gowrishankar-Palanisamy** [comment]
Status :

  Working on the bug that comes after saving the application with PDF Viewer

**Comment by Gowrishankar-Palanisamy** [comment]
@Paulson-Robert, @rameshpaulraj ,
Moving this ticket to testing, Need to do one round of testing from the testing team

**Comment by sakumar07** [comment]
@Gowrishankar-Palanisamy I have completed the testing for the and here is my observation.
https://github.com/SEMOSS/semoss-ui/issues/1684 issue number 1 still exists.

**Comment by Gowrishankar-Palanisamy** [comment]
Hi @neelneelneel ,
This ticket's PR was closed without being merged. Should I rework it or has the issue already been fixed ?
